import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  sizingSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Overview & Download',
    },
    {
      type: 'doc',
      id: 'preface',
      label: 'Preface',
    },
    {
      type: 'doc',
      id: 'why-inference-sizing',
      label: 'Why Inference Sizing Matters',
    },
    {
      type: 'html',
      value: '<div class="sidebar-section-label">Part I — Foundations</div>',
    },
    {
      type: 'category',
      label: '1 · Workload Characterization',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: '01-workload-characterization' },
      items: [
        { type: 'doc', id: '01-workload-characterization', label: '1.1 Why P99 Input Length Matters' },
        { type: 'doc', id: '01-workload-characterization', label: '1.2 Four Workload Archetypes' },
        { type: 'doc', id: '01-workload-characterization', label: '1.3 Sizing for Peak, Not Average' },
        { type: 'doc', id: '01-workload-characterization', label: '1.4 Online vs. Offline Batch' },
        { type: 'doc', id: '01-workload-characterization', label: '1.5 Model Routing and Cascading' },
      ],
    },
    {
      type: 'category',
      label: '2 · GPU Memory Sizing',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: '02-gpu-memory-sizing' },
      items: [
        { type: 'doc', id: '02-gpu-memory-sizing', label: '2.1 Model Weights: The Floor' },
        { type: 'doc', id: '02-gpu-memory-sizing', label: '2.2 KV Cache: The Hard Ceiling' },
        { type: 'doc', id: '02-gpu-memory-sizing', label: '2.3 Activations' },
        { type: 'doc', id: '02-gpu-memory-sizing', label: '2.4 Framework Overhead' },
        { type: 'doc', id: '02-gpu-memory-sizing', label: '2.5 Multi-LoRA Serving' },
        { type: 'doc', id: '02-gpu-memory-sizing', label: '2.6 Minimum GPU Count Formula' },
      ],
    },
    {
      type: 'category',
      label: '3 · The Roofline Model',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: '03-roofline-model' },
      items: [
        { type: 'doc', id: '03-roofline-model', label: '3.1 Arithmetic Intensity' },
        { type: 'doc', id: '03-roofline-model', label: '3.2 Prefill Is Compute-Bound' },
        { type: 'doc', id: '03-roofline-model', label: '3.3 Decode Is Memory-Bound' },
        { type: 'doc', id: '03-roofline-model', label: '3.4 Batch Size as Lever' },
        { type: 'doc', id: '03-roofline-model', label: '3.5 Hardware Strategy' },
      ],
    },
    {
      type: 'html',
      value: '<div class="sidebar-section-label">Part II — Optimization</div>',
    },
    {
      type: 'category',
      label: '4 · Quantization',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: '04-quantization' },
      items: [
        { type: 'doc', id: '04-quantization', label: '4.1 Weight-Only Quantization' },
        { type: 'doc', id: '04-quantization', label: '4.2 Activation Quantization' },
        { type: 'doc', id: '04-quantization', label: '4.3 KV Cache Quantization' },
        { type: 'doc', id: '04-quantization', label: '4.4 Sparsity' },
        { type: 'doc', id: '04-quantization', label: '4.5 Choosing the Right Approach' },
      ],
    },
    {
      type: 'category',
      label: '5 · Parallelism Strategy',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: '05-parallelism-strategy' },
      items: [
        { type: 'doc', id: '05-parallelism-strategy', label: '5.1 Tensor Parallelism' },
        { type: 'doc', id: '05-parallelism-strategy', label: '5.2 Pipeline Parallelism' },
        { type: 'doc', id: '05-parallelism-strategy', label: '5.3 Data Parallelism' },
        { type: 'doc', id: '05-parallelism-strategy', label: '5.4 Expert Parallelism (MoE)' },
        { type: 'doc', id: '05-parallelism-strategy', label: '5.5 Combining Strategies' },
        { type: 'doc', id: '05-parallelism-strategy', label: '5.6 The Interconnect' },
      ],
    },
    {
      type: 'category',
      label: '6 · Batching Strategy',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: '06-batching-strategy' },
      items: [
        { type: 'doc', id: '06-batching-strategy', label: '6.1 Static Batching: Why It Fails' },
        { type: 'doc', id: '06-batching-strategy', label: '6.2 The Scheduler' },
        { type: 'doc', id: '06-batching-strategy', label: '6.3 Continuous Batching' },
        { type: 'doc', id: '06-batching-strategy', label: '6.4 Chunked Prefill' },
        { type: 'doc', id: '06-batching-strategy', label: '6.5 Disaggregated Prefill-Decode' },
        { type: 'doc', id: '06-batching-strategy', label: '6.6 Speculative Decoding' },
        { type: 'doc', id: '06-batching-strategy', label: '6.7 Choosing the Right Strategy' },
      ],
    },
    {
      type: 'category',
      label: '7 · KV Cache Optimization',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: '07-kv-cache-optimization' },
      items: [
        { type: 'doc', id: '07-kv-cache-optimization', label: '7.1 PagedAttention' },
        { type: 'doc', id: '07-kv-cache-optimization', label: '7.2 Prefix Caching' },
        { type: 'doc', id: '07-kv-cache-optimization', label: '7.3 Cache-Aware Routing' },
        { type: 'doc', id: '07-kv-cache-optimization', label: '7.4 KV Cache Eviction' },
        { type: 'doc', id: '07-kv-cache-optimization', label: '7.5 KV Cache Quantization' },
        { type: 'doc', id: '07-kv-cache-optimization', label: '7.6 KV Cache Offloading' },
        { type: 'doc', id: '07-kv-cache-optimization', label: '7.7 What to Measure' },
      ],
    },
    {
      type: 'html',
      value: '<div class="sidebar-section-label">Part III — Production</div>',
    },
    {
      type: 'category',
      label: '8 · Latency-Throughput Curve',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: '08-latency-throughput-curve' },
      items: [
        { type: 'doc', id: '08-latency-throughput-curve', label: '8.1 The Shape of the Curve' },
        { type: 'doc', id: '08-latency-throughput-curve', label: '8.2 How to Generate the Curve' },
        { type: 'doc', id: '08-latency-throughput-curve', label: '8.3 From Benchmark to Fleet Size' },
        { type: 'doc', id: '08-latency-throughput-curve', label: '8.4 Start With the Question' },
        { type: 'doc', id: '08-latency-throughput-curve', label: '8.5 How Optimizations Shift the Curve' },
      ],
    },
    {
      type: 'category',
      label: '9 · Sizing Algorithm & Monitoring',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: '09-sizing-algorithm' },
      items: [
        { type: 'doc', id: '09-sizing-algorithm', label: '9.1 The Sizing Algorithm' },
        { type: 'doc', id: '09-sizing-algorithm', label: '9.2 The Utilization Trap' },
        { type: 'doc', id: '09-sizing-algorithm', label: '9.3 Production Monitoring' },
        { type: 'doc', id: '09-sizing-algorithm', label: '9.4 Production Guardrails' },
        { type: 'doc', id: '09-sizing-algorithm', label: '9.5 Heterogeneous Fleet' },
      ],
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },
    {
      type: 'doc',
      id: 'first-principles',
      label: 'First Principles, Last',
    },
  ],
};

export default sidebars;
